#! /bin/sh 
sxhkd &
picom &
setxkbmap -option grp:alt_shift_toggle us,ru
xsetroot -cursor_name Bibata-Modern-Classic &
xsetroot -cursor_name left_ptr &
setxkbmap -option ctrl:nocaps &
feh --bg-fil /home/deusbog/Pictures/arch.png &
polybar &
wmname LG3D &
lxpolkit &

bspc monitor -d 1 2 3 4 5 
bspc config border_width         1
bspc config window_gap           15
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config single_monocle	     true
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
bspc rule -a firefox desktop='^1'
bspc rule -a code desktop='^2'
bspc rule -a telegram-desktop desktop='^3'
bspc rule -a thunar desktop='^4'
bspc rule -a steam desktop='^5'
