local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
keymap("", "<s-f>", ":NvimTreeToggle<cr>", opts)
keymap("", "<s-s>", ":w<cr>", opts)
keymap("", "<s-q>", ":q!<cr>", opts)
keymap("", "<c-f>", ":Telescope find_files hidden=true<cr>", opts)
keymap("", "<c-g>", ":Telescope live_grep hidden=true<cr>", opts)
keymap("", "<c-r>", ":Telescope repo list<cr>", opts)
keymap("", "<c-left>", ":bprev<cr>", opts)
keymap("", "<c-right>", ":bnext<cr>", opts)
keymap("", "<s-left>", "<c-w>h", opts)
keymap("", "<s-right>", "<c-w>l", opts)
keymap("", "<s-down>", "<c-w>j", opts)
keymap("", "<s-up>", "<c-k>k", opts)
keymap("", "<c-h>", ":bprev<cr>", opts)
keymap("", "<c-l>", ":bnext<cr>", opts)
keymap("", "<s-h>", "<c-w>h", opts)
keymap("", "<s-l>", "<c-w>l", opts)
keymap("", "<s-j>", "<c-w>j", opts)
keymap("", "<s-k>", "<c-w>k", opts)
keymap("i", "jk", "<esc>", opts)
keymap("", "<c-p>", ":MarkdownPreview<cr>", opts)
keymap("", "<s-space>", ":nohlsearch<cr>", opts)
keymap("", "<s-t>", ":ToggleTerm<cr>", opts)
