local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
keymap("", "<s-f>", ":NvimTreeToggle<cr>", opts)
keymap("", "<c-s>", ":w<cr>", opts)
keymap("", "<c-q>", ":q!<cr>", opts)
keymap("", "<c-f>", ":Telescope find_files hidden=true<cr>", opts)
keymap("", "<c-g>", ":Telescope live_grep hidden=true<cr>", opts)
keymap("", "<c-r>", ":Telescope repo list<cr>", opts)
keymap("", "<s-left>", ":bprev<cr>", opts)
keymap("", "<s-right>", ":bnext<cr>", opts)
keymap("", "<c-left>", "<c-w>h", opts)
keymap("", "<c-right>", "<c-w>l", opts)
keymap("", "<c-down>", "<c-w>j", opts)
keymap("", "<c-up>", "<c-k>k", opts)
keymap("", "<s-h>", ":bprev<cr>", opts)
keymap("", "<s-l>", ":bnext<cr>", opts)
keymap("", "<c-h>", "<c-w>h", opts)
keymap("", "<c-l>", "<c-w>l", opts)
keymap("", "<c-j>", "<c-w>j", opts)
keymap("", "<c-k>", "<c-k>k", opts)
keymap("i", "jk", "<esc>", opts)
keymap("", "<c-p>", ":MarkdownPreview<cr>", opts)
keymap("", "<s-space>", ":nohlsearch<cr>", opts)
